server:
  port: 8080
  servlet.context-path: /api

spring:
  profiles.active: dev
  application.name: mandos-api

app.devices.api.url: https://mandos-smarthome-monitor.herokuapp.com/api/devices/monitor

---
#DEV CONFIGURATION
spring:
  profiles: dev
  data:
    mongodb:
      #authentication-database=admin
      #username=root
      #password=root
      database: mandos
      port: 27017
      host: localhost
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver: org.h2.Driver
#    username: sa

---
#PROD CONFIGURATION
spring:
  profiles: prod
  data.mongodb.uri: ${MONGODB_URI}?retryWrites=false
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver: org.h2.Driver
#    username: sa